config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
   registrations: 'public/customers/registrations',
   sessions:      'public/customers/sessions',
  }
  devise_for :admins, module: "admin/admins", path: "/admin"
  root :to => "public/homes#top"
  get "about" => "public/homes#about"
  resources :products, only: [:index, :show], controller: "public/products" do
    resources :comments, only: [:create, :destroy], controller: "public/comments"
    resource :favorites, only: [:create, :destroy], controller: "public/favorites"
  end
  resources :cart_products, only: [:index, :create, :update, :destroy], controller: "public/cart_products"
  delete "cart_products" => "public/cart_products#destroy_all", as: 'destroy_all'
  resources :customers, only: [:update], controller: "public/customers"
  get "customers/my_page" => "public/customers#show"
  get "customers/my_page/edit" => "public/customers#edit"
  get "customers/my_page/cancel" => "public/customers#cancel"
  patch "customers/my_page/cancel" => "public/customers#unsubscribe"
  post "orders/confirm" => "public/orders#confirm"
  get "orders/complete" => "public/orders#complete"
  resources :orders, only: [:index, :show, :new, :create], controller: "public/orders"
  resources :addresses, only: [:index, :create, :edit, :update, :destroy], controller: "public/addresses"
  get "search" => "public/searches#search"

  namespace :admin do
    get "/" => "orders#index"
    resources :products, only: [:index,:show, :new, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :order_products, only: [:update]
    get "search" => "searches#search"
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many	:addresses, dependent: :destroy
  has_many	:orders, dependent: :destroy
  has_many	:cart_products, foreign_key: "customer_id",	dependent: :destroy
  has_many	:products, through: :cart_products,	source: :product
  has_many  :comments, dependent: :destroy
  has_many  :favorites, dependent: :destroy
  has_many  :fav_products, through: :favorites, source: :product

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  # validates :is_deleted, presence: true

  paginates_per 10

  def self.search(model,keyword)
    if model == "customers" && keyword
      where(["last_name like? OR first_name like? OR email like?", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"])
    else
      all
    end
  end

  # is_deleted==trueの場合、ログインさせない
  def active_for_authentication?
    super && !(is_deleted?)
  end

  def inactive_message
    "既に退会済みです"
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

   before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customers_path
    else
      render "edit"
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <h3 class="bg-light p-3 my-4  d-inline-block">
    <%= "#{@customer.first_name}#{@customer.last_name}さんの会員情報編集" %>
  </h3>
  <div class="col-sm-12 mx-auto bg-light py-3">
    <%= form_with model: @customer, url: admin_customer_path(@customer.id), class: 'form-horizontal', local: true do |f| %>
      <%= render "public/customers/shared/error_messages", resource: @customer %>
      <div class="field form-group row">
        <p class="col-sm-3 control-label h5">会員ID</p>
        <p><%= @customer.id %></p>
      </div>

      <div class="field form-group row">
        <%= f.label :"氏名", class: "col-sm-3 control-label h5" %>
        <%= f.text_field :first_name, autofocus: true, class: "col-sm-2" %>
        <%= f.text_field :last_name, autofocus: true, class: "col-sm-2 ml-5" %>
      </div>

      <div class="field form-group row">
        <%= f.label :"フリガナ", class: "col-sm-3 control-label h5" %>
        <%= f.text_field :first_name_kana, autofocus: true, class: "col-sm-2" %>
        <%= f.text_field :last_name_kana, autofocus: true, class: "col-sm-2 ml-5" %>
      </div>

      <div class="field form-group row">
        <%= f.label :"郵便番号", class: "col-sm-3 control-label h5" %>
        <%= f.text_field :postal_code, autofocus: true, class: "col-sm-2" %>
      </div>

      <div class="field form-group row">
        <%= f.label :"住所", class: "col-sm-3 control-label h5" %>
        <%= f.text_field :address, autofocus: true, class: "col-sm-6" %>
      </div>

      <div class="field form-group row">
        <%= f.label :"電話番号", class: "col-sm-3 control-label h5" %>
        <%= f.text_field :telephone_number, autofocus: true, class: "col-sm-2" %>
      </div>

      <div class="field form-group row">
        <%= f.label :"メールアドレス", class: "col-sm-3 control-label h5" %>
        <%= f.text_field :email, autofocus: true, class: "col-sm-2" %>
      </div>

      <div class="field form-group row">
        <%= f.label :"会員ステータス", class: "col-sm-3 control-label h5" %>
        <div>
          <%= f.radio_button :is_deleted, :false, include_hidden: false %>
          <%= f.label :"有効", class: "control-label" %>
        </div>
        <div class="ml-3">
          <%= f.radio_button :is_deleted, :true, include_hidden: true %>
          <%= f.label :"退会", class: "control-label" %>
        </div>
      </div>

      <div class="actions row">
        <%= f.submit "変更を保存", class: "btn btn-success col-sm-2 offset-sm-3 p-2 mt-3" %>
      </div>
     <% end %>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-9 mx-auto">
      <h3 class="bg-light p-3 my-4 d-inline-block">会員一覧</h3>
      <table class="table ml-5">
        <tbody>
          <tr class="bg-light">
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>

          <% @customers.each do |customers| %>
            <tr>
              <td><%= customers.id %></td>
              <td>
                <%= link_to admin_customer_path(customers.id) do %>
                  <u class="text-secondary">
                    <%= "#{customers.first_name}#{customers.last_name}" %>
                  </u>
                <% end %>
              </td>
              <td><%= customers.email %></td>
              <% if customers.is_deleted == false %>
                <td class="text-success">有効</td>
              <% else %>
                <td class="text-secondary">退会</td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>

      <div>
        <%= paginate @customers, class:"text-center" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="col-md-9">
    <h3 class="bg-light p-3 my-4 d-inline-block">
      <%= "#{@customer.first_name}#{@customer.last_name}さんの会員詳細" %>
    </h3>

    <table class="table table-bordered">
      <tr>
        <th class="table-secondary">会員ID</th>
        <td><%= @customer.id %></td>
      </tr>
      <tr>
        <th class="table-secondary">氏名</th>
        <td><%= "#{@customer.first_name}　#{@customer.last_name}" %></td>
      </tr>
      <tr>
        <th class="table-secondary">フリガナ</th>
        <td><%= "#{@customer.first_name_kana}　#{@customer.last_name_kana}" %></td>
      </tr>
      <tr>
        <th class="table-secondary">郵便番号</th>
        <td><%= @customer.postal_code %></td>
      </tr>
      <tr>
        <th class="table-secondary">住所</th>
        <td><%= @customer.address %></td>
      </tr>
      <tr>
        <th class="table-secondary">電話番号</th>
        <td><%= @customer.telephone_number %></td>
      </tr>
      <tr>
        <th class="table-secondary">メールアドレス</th>
        <td><%= @customer.email %></td>
      </tr>
      <tr>
        <th class="table-secondary">会員ステータス</th>
        <% if @customer.is_deleted == false %>
          <td class="text-success">有効</td>
        <% else %>
          <td class="text-secondary">退会</td>
        <% end %>
      </tr>
    </table>
    <div class="text-center">
      <%= link_to "編集する", edit_admin_customer_path(@customer.id), class:"btn btn-success ml-5" %>
      <%= link_to "注文履歴一覧を見る", admin_orders_path, class:"btn btn-primary ml-5" %>
    </div>
  </div>
</div>