config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
   registrations: 'public/customers/registrations',
   sessions:      'public/customers/sessions',
  }
  devise_for :admins, module: "admin/admins", path: "/admin"
  root :to => "public/homes#top"
  get "about" => "public/homes#about"
  resources :products, only: [:index, :show], controller: "public/products" do
    resources :comments, only: [:create, :destroy], controller: "public/comments"
    resource :favorites, only: [:create, :destroy], controller: "public/favorites"
  end
  resources :cart_products, only: [:index, :create, :update, :destroy], controller: "public/cart_products"
  delete "cart_products" => "public/cart_products#destroy_all", as: 'destroy_all'
  resources :customers, only: [:update], controller: "public/customers"
  get "customers/my_page" => "public/customers#show"
  get "customers/my_page/edit" => "public/customers#edit"
  get "customers/my_page/cancel" => "public/customers#cancel"
  patch "customers/my_page/cancel" => "public/customers#unsubscribe"
  post "orders/confirm" => "public/orders#confirm"
  get "orders/complete" => "public/orders#complete"
  resources :orders, only: [:index, :show, :new, :create], controller: "public/orders"
  resources :addresses, only: [:index, :create, :edit, :update, :destroy], controller: "public/addresses"
  get "search" => "public/searches#search"

  namespace :admin do
    get "/" => "orders#index"
    resources :products, only: [:index,:show, :new, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :order_products, only: [:update]
    get "search" => "searches#search"
  end
end

app/models/product.rb
class Product < ApplicationRecord

  has_many  :cart_products,	foreign_key: "product_id", dependent: :destroy
  has_many  :customer, through: :cart_products,	source: :customer
  has_many  :order_products, foreign_key: "product_id",	dependent: :destroy
  has_many  :order, through: :order_products,	source: :order
  has_many  :comments, dependent: :destroy
  has_many  :favorites, dependent: :destroy
  belongs_to  :genre
  attachment :image

  def self.review_persent(star,comment)
    case star
    when 5
      (self.where("rate = 5").count.to_f / self.pluck(:rate).count.to_f * 100).to_i
    when 4
      (self.where("rate = 4").count.to_f / self.pluck(:rate).count.to_f * 100).to_i
    when 3
      (self.where("rate = 3").count.to_f / self.pluck(:rate).count.to_f * 100).to_i
    when 2
      (self.where("rate = 2").count.to_f / self.pluck(:rate).count.to_f * 100).to_i
    when 1
      (self.where("rate = 1").count.to_f / self.pluck(:rate).count.to_f * 100).to_i
    end
  end

  def add_tax_price
      (self.price * 1.10).round
  end

  def self.search(model,keyword)
    if model == "products" && keyword
      where(["name like? OR introduction like?", "%#{keyword}%", "%#{keyword}%"])
    else
      all
    end
  end

  def self.all_month(product)
    jan = Date.today.beginning_of_year
    feb = Date.today.beginning_of_year.next_month(1)
    mar = Date.today.beginning_of_year.next_month(2)
    apr = Date.today.beginning_of_year.next_month(3)
    may = Date.today.beginning_of_year.next_month(4)
    jun = Date.today.beginning_of_year.next_month(5)
    jul = Date.today.beginning_of_year.next_month(6)
    aug = Date.today.beginning_of_year.next_month(7)
    sep = Date.today.beginning_of_year.next_month(8)
    oct = Date.today.beginning_of_year.next_month(9)
    nov = Date.today.beginning_of_year.next_month(10)
    dec = Date.today.beginning_of_year.next_month(11)

    data = {"#{jan.month}月" => product.order_products.where(created_at: jan..feb).sum(:amount),#1月
      "#{feb.month}月" => product.order_products.where(created_at: feb..mar).sum(:amount),#2月
      "#{mar.month}月" => product.order_products.where(created_at: mar..apr).sum(:amount),#3月
      "#{apr.month}月" => product.order_products.where(created_at: apr..may).sum(:amount),#4月
      "#{may.month}月" => product.order_products.where(created_at: may..jun).sum(:amount),#5月
      "#{jun.month}月" => product.order_products.where(created_at: jun..jul).sum(:amount),#6月
      "#{jul.month}月" => product.order_products.where(created_at: jul..aug).sum(:amount),#7月
      "#{aug.month}月" => product.order_products.where(created_at: aug..sep).sum(:amount),#8月
      "#{sep.month}月" => product.order_products.where(created_at: sep..oct).sum(:amount),#9月
      "#{oct.month}月" => product.order_products.where(created_at: oct..nov).sum(:amount),#10月
      "#{nov.month}月" => product.order_products.where(created_at: nov..dec).sum(:amount),#11月
      "#{dec.month}月" => product.order_products.where(created_at: dec..dec.end_of_month).sum(:amount)#12月
    }
  end

  def favorited_by?(customer)
    favorites.where(customer_id: customer.id).exists?
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @products = Product.all
    @products_page = Product.page(params[:page]).per(10)
  end

  def show
    @product = Product.find(params[:id])
    @comments = @product.comments.all.page(params[:page])
    @rate_avg = @comments.average(:rate).to_i
    @product_order_count = @product.order.count
    @product_sale_count = @product.order_products.sum(:amount)
    @sales_price = @product_sale_count * @product.price
    @sale_data =Product.all_month(@product)
    if @comments.present?
      @data = {"5" => Comment.review_persent(5, @comments),
      "4" => Comment.review_persent(4, @comments),
      "3" => Comment.review_persent(3, @comments),
      "2" => Comment.review_persent(2, @comments),
      "1" => Comment.review_persent(1, @comments)}
    end
  end

  def new
    @product = Product.new
    @genres = Genre.all
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_product_path(@product), notice: "新しい商品を追加しました！"
    else
      render "new"
    end
  end

  def edit
    @product = Product.find(params[:id])
    @genres = Genre.all
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admin_product_path(@product), notice: "商品を編集しました！"
    else
      render "edit"
    end
  end

  private

    def product_params
      params.require(:product).permit(:genre_id, :name, :image, :introduction, :price, :is_active)
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9 mx-auto">
      <h3 class="bg-light p-3 my-4 d-inline-block">商品編集</h3>
      <%= form_with model: @product, url: admin_product_path, id: 'edit_product', class: 'edit_product form-horizontal', local: true do |f| %>
        <%= render "public/customers/shared/error_messages", resource: @product %>

        <div class="field form-group row">
          <%= f.label :"商品画像", class: "col-md-3 control-label h5" %>
          <%= f.attachment_field :image, class: "col-md-5 form-control-file user_image" %>
        </div>

        <div class="field form-group row">
          <%= f.label :"商品名", class: "col-md-3 control-label h5" %>
          <%= f.text_field :name, placeholder: "商品名", autofocus: true, class: "col-md-5" %>
        </div>

        <div class="field form-group row">
          <%= f.label :"商品説明", class: "col-md-3 control-label h5" %>
          <%= f.text_area :introduction, placeholder: "ここに説明文を記述します", size: "20x10", class: "col-md-5" %>
        </div>

        <div class="field form-group row">
          <%= f.label :"ジャンル", class: "col-md-3 control-label h5" %>
          <%= f.collection_select :genre_id, @genres, :id, :name %>
        </div>

        <div class="field form-group row">
          <%= f.label :"販売価格", class: "col-md-3 control-label h5" %>
          <%= f.text_field :price, placeholder: "1000", class: "col-md-5" %><p class="mt-3 ml-2 h5">円</p>
        </div>

        <div class="field form-group row">
          <%= f.label :"販売ステータス", class: "col-md-3 control-label h5" %>
          <div>
            <%= f.radio_button :is_active, true %>
            <%= f.label :is_active, "販売中", value: true %>
          </div>
          <div>
            <%= f.radio_button :is_active, false %>
            <%= f.label :is_active, "販売停止中", value: false %>
          </div>
        </div>

        <div class="actions row">
          <%= f.submit "編集する", class: "btn btn-success btn-block col-md-3 offset-sm-3" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-9 mx-auto">
      <h3 class="bg-light p-3 my-4 d-inline-block">商品一覧</h3>
      <h3 class="p-3 my-4 d-inline-block offset-sm-8"><%= link_to "商品追加", new_admin_product_path, class: "btn btn-lg btn-success" %></h3>
      <table class="table ml-5">
        <thead>
          <tr class="bg-light">
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>

        <tbody>
          <% @products.each do |product| %>
            <tr>
              <td><%= product.id %></td>
              <td>
                <%= link_to admin_product_path(product) do %>
                  <u class="text-secondary">
                    <%= product.name %>
                  </u>
                <% end %>
              </td>
              <td><%= product.price.to_s(:delimited) %></td>
              <td><%= product.genre.name %></td>
              <td>
                <% if product.is_active == true %>
                  <p class="text-success">販売中</p>
                <% else %>
                  <p class="text-secondary">販売停止中</p>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <div>
        <%= paginate @products_page, class:"text-center" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9 mx-auto">
      <h3 class="bg-light p-3 my-4 d-inline-block">商品新規登録</h3>
      <%= form_with model: @product, url: admin_products_path, id: 'new_product', class: 'new_product form-horizontal', local: true do |f| %>
        <%= render "public/customers/shared/error_messages", resource: @product %>

        <div class="field form-group row">
          <%= f.label :"商品画像", class: "col-md-3 control-label h5" %>
          <%= f.attachment_field :image, class: "col-md-5 form-control-file user_image" %>
        </div>

        <div class="field form-group row">
          <%= f.label :"商品名", class: "col-md-3 control-label h5" %>
          <%= f.text_field :name, placeholder: "商品名", autofocus: true, class: "col-md-5" %>
        </div>

        <div class="field form-group row">
          <%= f.label :"商品説明", class: "col-md-3 control-label h5" %>
          <%= f.text_area :introduction, placeholder: "ここに説明文を記述します", size: "20x10", class: "col-md-5" %>
        </div>

        <div class="field form-group row">
          <%= f.label :"ジャンル", class: "col-md-3 control-label h5" %>
          <%= f.collection_select :genre_id, @genres, :id, :name %>
        </div>

        <div class="field form-group row">
          <%= f.label :"販売価格", class: "col-md-3 control-label h5" %>
          <%= f.text_field :price, placeholder: "1000", class: "col-md-5" %><p class="mt-3 ml-2 h5">円</p>
        </div>

        <div class="field form-group row">
          <%= f.label :"販売ステータス", class: "col-md-3 control-label h5" %>
          <div>
            <%= f.radio_button :is_active, true %>
            <%= f.label :is_active, "販売中", value: true %>
          </div>
          <div>
            <%= f.radio_button :is_active, false %>
            <%= f.label :is_active, "販売停止中", value: false %>
          </div>
        </div>

        <div class="actions row">
          <%= f.submit "新規登録", class: "btn btn-success btn-block col-md-3 offset-md-3" %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/admin/products/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 mt-5">
      <%= attachment_image_tag @product, :image, :fill, 480, 340 %>
    </div>

    <div class="col-6 mt-5">
      <div>
        <label class="h5">商品名</label>
        <p class="d-inline-block ml-4 h5"><%= @product.name %></p>
      </div>

      <div>
        <label class="h5">商品説明</label>
        <p class="d-inline-block ml-4 h5"><%= @product.introduction %></p>
      </div>

      <div>
        <label class="h5">ジャンル</label>
        <p class="d-inline-block ml-4 h5"><%= @product.genre.name %></p>
      </div>

      <div>
        <label class="h5">税込価格(税抜価格)</label>
        <p class="d-inline-block ml-4"><%= @product.price.to_s(:delimited) %>(<%= @product.add_tax_price.to_s(:delimited) %>)</p>
      </div>

      <div>
        <label class="h5">販売ステータス</label>
        <% if @product.is_active == true %>
          <p class="text-success d-inline-block ml-4 h5">販売中</p>
        <% else %>
          <p class="text-secondary d-inline-block ml-4 h5">販売停止中</p>
        <% end %>
      </div>

      <div class="actions row">
        <%= link_to "編集する", edit_admin_product_path(@product), class: "btn btn-success btn-block mt-4 col-sm-3 offset-sm-3" %>
      </div>
    </div>
  </div>

  <div class="row mt-5 pt-5">
    <div class="col-3 ">
      <h2>売上情報</h2>
      <div class="ml-3 mt-3">
        <p>注文件数:<%= @product_order_count %></p>
        <p>販売件数:<%= @product_sale_count %></p>
        <p>総売上げ：<%= @sales_price.to_s(:delimited) %>円</p>
      </div>
    </div>
    <div class="col-7">
      <%= column_chart @sale_data %>
    </div>
  </div>

  <div class="row">
    <div class="col-4 mt-5 pt-5">
      <h2>お客様の声</h2>
      <div id="rate_avg"></div>
      <%= bar_chart @data, colors: ["orange"], min: 0, max: 100 %>
    </div>

    <div class="col-7 offset-1 mt-5 pt-5">
      <div class="my-2">
        <% @comments.each do |comment| %>
          <h4 class="mt-5"><%= comment.title %></h4>
          <div class="d-inline-block">
            <span class="ml-2" id="rate_<%= comment.id %>"></span>
              <script>
                $('#rate_<%= comment.id %>').raty({
                  size: 20,
                  starOff:  '<%= asset_path('star-off.png') %>',
                  starOn : '<%= asset_path('star-on.png') %>',
                  starHalf: '<%= asset_path('star-half.png') %>',
                  half: true,
                  readOnly: true,
                  score: <%= comment.rate %>,
                });
              </script>
            <span class="ml-5 pl-5"><%= comment.created_at.strftime("%Y/%m/%d") %></span>
          </div>
          <p class="d-block mt-3"><%= comment.comment %></p>
          <%= link_to "#{comment.customer.first_name}#{comment.customer.last_name}", admin_customer_path(comment.customer_id) %>
        <% end %>
      </div>
    </div>
  </div>
  <%= paginate @comments %>
</div>

<script>
  $('#rate_avg').raty({
    size: 20,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    half: true,
    readOnly: true,
    score: <%= @rate_avg %>
  });
</script>